###
GET http://localhost:4000/api/posts

###
GET http://localhost:4000/api/posts/sender
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxMjc3OSwiZXhwIjoxNzMzNDE2Mzc5fQ.f1WtONbQFvgo2iFUeJNH9xSz47zswdFO35pXj13qDpQ
###
POST  http://localhost:3000/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzQxNzI5MWYwYTQ0M2ZlMDc3OGU4MSIsImlhdCI6MTczNTY2MTM2NSwiZXhwIjoxNzM1NjY0OTY1fQ.PkYGBZP0LMHdDnrChdh5TefuUnQFs4WbsZLGymtRWDw
Content-Type: application/json

{
    "content": "this is גדכגדכגדכגדmessage",
    "title": "this is title"
}

###
GET http://localhost:3000/api/posts/677417da1f0a443fe0778e86

###
PUT http://localhost:3000/api/posts/like/6773da72aeb2d8fb6de88936
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzY0ODNjMWYwYTQ0M2ZlMDc3OGVkZSIsImlhdCI6MTczNTgwNjQ1NCwiZXhwIjoxNzM1ODEwMDU0fQ.YcpALxMgb9pncqTQCeBsFEuIunlFkg-h6vjmpPD9aRg

###
PUT  http://localhost:3000/api/posts/6773da72aeb2d8fb6de88936
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFkODQ5MzhlMjc1NjQyNmUwM2UwZiIsImlhdCI6MTczMzQ3MjU4OCwiZXhwIjoxNzMzNDc2MTg4fQ.YW6rZLe2E3QUwd8ojOKASv5TJGVBFePygNMK0zJJxeo
Content-Type: application/json

{
    "message": "update message"
}

//npm run dev:watch
////////////////////////////////////////////// comments \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
###
POST  http://localhost:3000/api/comment
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzQxNzI5MWYwYTQ0M2ZlMDc3OGU4MSIsImlhdCI6MTczNTY2MjY3NywiZXhwIjoxNzM1NjY2Mjc3fQ.l0rafYalzL4ZN_Dy6mAdFnd9lSEZ5kv-hKRVX4TBUUA
Content-Type: application/json

{
    "content": "this is the fisdfdsfdsfrst דגכגדכדגכגדכגכגד ",
    "postId": "677417da1f0a443fe0778e86"
}

###
GET http://localhost:3000/api/comment/6751d2ad29babb95e23add2e

###
PUT http://localhost:4000/api/comment/6751d2ad29babb95e23add2e
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzMzNDE3OTE1fQ.dWORrIE4ZUFWQt4jaXMAzKw1UnmbIXHL6XJ5A92Yrxc
Content-Type: application/json

{
    "content": "this is updated comment"
}

###
DELETE  http://localhost:3000/api/comment/6751d2ad29babb95e23add2e
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzMzNDE3OTE1fQ.dWORrIE4ZUFWQt4jaXMAzKw1UnmbIXHL6XJ5A92Yrxc

###
GET http://localhost:3000/api/comment/get-all-comments/677417da1f0a443fe0778e86
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzQxNzI5MWYwYTQ0M2ZlMDc3OGU4MSIsImlhdCI6MTczNTY2MTM2NSwiZXhwIjoxNzM1NjY0OTY1fQ.PkYGBZP0LMHdDnrChdh5TefuUnQFs4WbsZLGymtRWDw




  //////////////////////////////////// auth /////////////////////////


###
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "em@gmail.com",
    "password": "12346"
}

###
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "em@gmail.com",
    "password": "12346",
    "userName": "example"
   
}

###
GET  http://localhost:3000/api/auth/refreshToken
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWQ3MTExMGQ4M2Y2YzUxNWZjNjQ4NiIsImlhdCI6MTczNDE3NzA3OSwiZXhwIjoxNzM0NzgxODc5fQ.ygMv3FvoCSsDn2V8pXlTNU920UUB60wpy0lb4dZKrRA"
}

###
POST  http://localhost:4000/api/auth/logout
Content-Type: application/json

{
   "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzY3ZDYzYTM4NjhlMDI2MTdjODBmYSIsImlhdCI6MTczNTgxODc4NiwiZXhwIjoxNzM2NDIzNTg2fQ._OZriOMXUSVboYXqQFWBLwNk-6eJ-lWvvA-De2PLSSE" 
}
###
GET  http://localhost:3000/api/auth/logout
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWQ3MTExMGQ4M2Y2YzUxNWZjNjQ4NiIsImlhdCI6MTczNDE3NzA3OSwiZXhwIjoxNzM0NzgxODc5fQ.ygMv3FvoCSsDn2V8pXlTNU920UUB60wpy0lb4dZKrRA"
}