###
GET http://localhost:4000/api/posts

###
GET http://localhost:4000/api/posts/sender
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxMjc3OSwiZXhwIjoxNzMzNDE2Mzc5fQ.f1WtONbQFvgo2iFUeJNH9xSz47zswdFO35pXj13qDpQ
###
POST  http://localhost:4000/api/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzMzNDE3OTE1fQ.dWORrIE4ZUFWQt4jaXMAzKw1UnmbIXHL6XJ5A92Yrxc
Content-Type: application/json

{
    "message": "Shrivker gay"
}

###
GET http://localhost:4000/api/posts/6735e5433fc7b7ca4f640709


###
PUT  http://localhost:4000/api/posts/6751cf3a155423d2aa357f95
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzMzNDE3OTE1fQ.dWORrIE4ZUFWQt4jaXMAzKw1UnmbIXHL6XJ5A92Yrxc
Content-Type: application/json

{
    "message": "update message"
}

//npm run dev:watch
////////////////////////////////////////////// comments \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
###
POST  http://localhost:4000/api/comment
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzMzNDE3OTE1fQ.dWORrIE4ZUFWQt4jaXMAzKw1UnmbIXHL6XJ5A92Yrxc
Content-Type: application/json

{
    "content": "this is the first comment ",
    "postId": "6751cf3a155423d2aa357f95"
}

###
GET http://localhost:4000/api/comment/6751d2ad29babb95e23add2e
###
PUT http://localhost:4000/api/comment/6751d2ad29babb95e23add2e
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzMzNDE3OTE1fQ.dWORrIE4ZUFWQt4jaXMAzKw1UnmbIXHL6XJ5A92Yrxc
Content-Type: application/json

{
    "content": "this is updated comment"
}

###
DELETE  http://localhost:4000/api/comment/6751d2ad29babb95e23add2e
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzMzNDE3OTE1fQ.dWORrIE4ZUFWQt4jaXMAzKw1UnmbIXHL6XJ5A92Yrxc

###
GET http://localhost:4000/api/comment/get-all-comments/6735e5433fc7b7ca4f640709
  //////////////////////////////////// auth /////////////////////////


###
POST  http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456"
}

###
POST  http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456"
}

###
GET  http://localhost:4000/api/auth/refreshToken
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQwOTExNywiZXhwIjoxNzM0MDEzOTE3fQ.aapllS1PxXOZ1eKD1-MTMFlBSqVOzNIFt6fMvsOGldE"
}

###
GET  http://localhost:4000/api/auth/logout
Content-Type: application/json

{
   "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzM0MDE5MTE1fQ.HyIQk3wr-pjP_bRxjSTQ1WcK1H8UaTynSiphXff0wWQ" 
}
###
GET  http://localhost:4000/api/users/logout
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTFiNGY4ZDE1NTBjYTA2ZmUyNmJjYiIsImlhdCI6MTczMzQxNDMxNSwiZXhwIjoxNzM0MDE5MTE1fQ.HyIQk3wr-pjP_bRxjSTQ1WcK1H8UaTynSiphXff0wWQ"
}